---
version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
    vendor: true
    versioning-strategy: increase
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "vernier"
